@NET_Project.Server_HostAddress = https://localhost:7175

GET {{NET_Project.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{NET_Project.Server_HostAddress}}/weatherforecast

###
